import { Providers } from '~/components/Providers/Providers';
import './globals.scss';

export const metadata = {
    title: 'News',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="mt-20">
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
